version: "3.8"

services:
  registry:
    restart: always
    image: registry:2.8.1
    labels:
      kompose.controller.type: "statefulset"
      kompose.volume.size: 15Gi
      kompose.service.expose: "{{ .Values.host }}"
      kompose.service.expose.ingress-class-name: "nginx"
      kompose.service.expose.tls-secret: "argiago-registry-prod-secret"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.org/configuration-snippet: |
        proxy_body_size 0;
        client_max_body_size 0;
    ports:
      - 80:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry:/var/lib/registry
    configs:
      - source: registry-conf
        target: /etc/docker/registry/config.yml
    secrets:
      - source: registry-auth
        target: /auth/htpasswd

configs:
  registry-conf:
    file: .raw/config.yaml
secrets:
  registry-auth:
    file: .raw/htpasswd

volumes:
  registry:
    driver: local
