apiVersion: v1
kind: Service
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates -n registry
    kompose.controller.type: statefulset
    kompose.service.expose: {{ .Values.host }}
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: argiago-registry-prod-secret
    kompose.version: 1.31.0 (HEAD)
    kompose.volume.size: 15Gi
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.org/configuration-snippet: |
      proxy_body_size 0;
      client_max_body_size 0;
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
  namespace: registry
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    io.kompose.service: registry
status:
  loadBalancer: {}
