apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
    kompose.controller.type: statefulset
    kompose.service.expose: {{ .Values.host }}
    kompose.service.expose.ingress-class-name: nginx
    kompose.version: 1.28.0 (HEAD)
    kompose.volume.size: 15Gi
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registry
  serviceName: registry
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/registry-default: "true"
        io.kompose.service: registry
    spec:
      containers:
        - env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
          image: registry:2.8.1
          name: registry
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /etc/docker/registry/config.yml
              name: registry-conf
              subPath: config.yml
            - mountPath: /auth
              name: registry-auth
            - mountPath: /var/lib/registry
              name: registry
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yml
            name: registry-conf
          name: registry-conf
        - name: registry-auth
          secret:
            items:
              - key: registry-auth
                path: htpasswd
            secretName: registry-auth
        - name: registry
          persistentVolumeClaim:
            claimName: registry
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: registry
        name: registry
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
      status: {}
status:
  replicas: 0
